- name: System bootstrap (root only)
  hosts: local
  connection: local
  become: false # Chạy ansible bằng root
  roles:
    - system
  tags: [system]


- name: User environment setup (single user)
  hosts: local
  connection: local
  become: false
  vars:
    user: "{{ target_user }}"
  roles:
    - users
  tags: [users]
