# TODO: Clone oh-my-zsh repo bằng git module và chạy installer từ local thay vì curl pipe to shell
- name: Install Oh My Zsh
  shell: |
    sh -c "$(curl -fsSL {{ oh_my_zsh_install_url }})" "" --unattended
  args:
    creates: "{{ user.home }}/.oh-my-zsh"